export const manifestTemplate = {
  "format_version": 2,
  "header": {
    "name": "Custom Behavior Pack",
    "description": "Generated by Addon Visual Coding Tool",
    "uuid": "",
    "version": [1, 0, 0],
    "min_engine_version": [1, 21, 0],
    "authors": ["TechRope"]
  },
  "modules": [
    {
      "type": "script",
      "language": "javascript",
      "uuid": "",
      "entry": "scripts/main.js",
      "version": [1, 0, 0]
    }
  ],
  "dependencies": [
    {
      "module_name": "@minecraft/server",
      "version": "1.11.0"
    }
  ]
}; 